version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: eulabs123
      MYSQL_DATABASE: eulabs
      MYSQL_USER: user
      MYSQL_PASSWORD: eulabs123
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
