definitions:
  CreateProductRequest:
    properties:
      description:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  CreateProductResponse:
    properties:
      id:
        type: integer
    type: object
  GetAllProductsResponse:
    properties:
      pagination:
        $ref: '#/definitions/ProductPagination'
      products:
        items:
          $ref: '#/definitions/Product'
        type: array
    type: object
  GetByProductIDResponse:
    properties:
      create_at:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      update_at:
        type: string
    type: object
  Product:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      updated_at:
        type: string
    type: object
  ProductPagination:
    properties:
      limit:
        type: integer
      offset:
        type: integer
      total:
        type: integer
    type: object
  UpdateProductRequest:
    properties:
      description:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
paths:
  /eulabs/v1/health:
    get:
      consumes:
      - application/json
      description: healthcheck router
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: healthcheck router
      tags:
      - Healthcheck
  /eulabs/v1/product:
    get:
      consumes:
      - application/json
      description: get all products by pagination router
      parameters:
      - description: limit
        in: query
        name: limit
        type: integer
      - description: offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GetAllProductsResponse'
        "500":
          description: Internal Server Error
          schema: {}
      summary: get all products by pagination router
      tags:
      - Product
    post:
      consumes:
      - application/json
      description: create product router
      parameters:
      - description: create product
        in: body
        name: createProductRequest
        required: true
        schema:
          $ref: '#/definitions/CreateProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/CreateProductResponse'
        "500":
          description: Internal Server Error
          schema: {}
      summary: create product router
      tags:
      - Product
  /eulabs/v1/product/{id}:
    delete:
      consumes:
      - application/json
      description: delete product router
      parameters:
      - description: id product
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Product deleted successfully
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema: {}
      summary: delete product router
      tags:
      - Product
    get:
      consumes:
      - application/json
      description: get product by id router
      parameters:
      - description: id product
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GetByProductIDResponse'
        "500":
          description: Internal Server Error
          schema: {}
      summary: get product by id router
      tags:
      - Product
    put:
      consumes:
      - application/json
      description: update product router
      parameters:
      - description: id product
        in: path
        name: id
        required: true
        type: integer
      - description: update product
        in: body
        name: updateProductRequest
        required: true
        schema:
          $ref: '#/definitions/UpdateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Product updated successfully
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema: {}
      summary: update product router
      tags:
      - Product
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
